apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tg-token
  namespace: tg-personal-assistant-dev
spec:
  encryptedData:
    tg_token: AgAFJWI6pr3CUM3ZUavw/v3DZweJsXAndh3+I+TF5Et8tAg3o09HzrsvlfXolCqqH/a3xDiRCNg6GtfZuksUdRiSZvMPuhJS++C4IJb9cvf1UcGLN/AV0bI861HulHcWF4XhI0/T1JY6z4ZAVMZ/7iOqPsTmT57hBu3WNoYrKA5hbah4XQHQ7xjmtmYSnMUSXTJarw4SJhGoHli34bK9xq4l7Hl5JD/hazcqLvZJZ4VcDE86gzwEpX1zBJnBeBcSoaJt4MSHwLFvl+Dc5MewQItimNX7hC5/QqIeF75DCVR2D+Ib1QdDHDVYTIB4lDGditoCrGn0qDvL9kf39c3q+N8/bSqYw104KAkwf5Yr6LnrTPck6liljuQnwA6m5DAdgya6RRrX4AMnDU+iWeRgxJmP+EM6qrE/EsNUZKn86sc8TAIB0AyGtKcqi0UV2XV9Rfy2M3w849afRFMA8cyQMFJfeVd/YFkBpfO9Kcb3Gjbg0dKyXVfkuiHji9GzFdlyPgqxkWldDvW8VZuPAlHUVUkKU/iwnAY4eWIGh+fH/A3DnYsoJLLhwhcw+nxfq/bWJ6WdzofKDUrADCFUq9bbPgicBoaFVYUFMHahGvkZ+JS35A1NVP9UDgWaLcWmFC/BAs88tBmGdTylNXlobH/T3ET0cJigslLuC090ZJhrnLF3+szT5FWyvme4VD35I1i0w7L6igaXL3E2c80Or1RH/G9JBFmEzl2t4K7Y5YFP2QQkt85kuqSgjz4C76t1+T5a
  template:
    metadata:
      creationTimestamp: null
      name: tg-token
      namespace: tg-personal-assistant-dev
